"""add_oauth_fields_to_user

Revision ID: 6384736f4fda
Revises: 3fd25b244281
Create Date: 2024-12-27 16:51:11.978219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6384736f4fda'
down_revision: Union[str, None] = '3fd25b244281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_expiry')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
